export declare enum EnvironmentType {
    DEV = "DEV",
    TEST = "TEST",
    PROD = "PROD"
}
export declare enum UserRole {
    VIEWER = "VIEWER",
    BUILDER = "BUILDER",
    RELEASE_MANAGER = "RELEASE_MANAGER",
    ADMIN = "ADMIN",
    PLATFORM_ADMIN = "PLATFORM_ADMIN"
}
export declare enum TemplateClass {
    CERTIFIED = "CERTIFIED",
    STARTER = "STARTER"
}
export declare enum BusinessObject {
    VENDOR = "VENDOR",
    PURCHASE_ORDER = "PURCHASE_ORDER",
    INVOICE = "INVOICE",
    GENERIC = "GENERIC"
}
export declare enum ConnectionFamily {
    REST_OPENAPI = "REST_OPENAPI",
    SFTP_FILE = "SFTP_FILE",
    JDBC_SQL = "JDBC_SQL",
    S3 = "S3",
    WEBHOOK = "WEBHOOK",
    SCHEDULER = "SCHEDULER"
}
export declare enum IntegrationStatus {
    DRAFT = "DRAFT",
    IN_TEST = "IN_TEST",
    LIVE = "LIVE",
    ATTENTION_NEEDED = "ATTENTION_NEEDED",
    PAUSED = "PAUSED"
}
export declare enum ArtifactStatus {
    DRAFT = "DRAFT",
    SUBMITTED = "SUBMITTED",
    APPROVED = "APPROVED",
    REJECTED = "REJECTED",
    DEPLOYED = "DEPLOYED"
}
export declare enum MappingType {
    DIRECT = "DIRECT",
    CONSTANT = "CONSTANT",
    DERIVED = "DERIVED",
    LOOKUP = "LOOKUP",
    CONDITIONAL = "CONDITIONAL"
}
export declare enum MappingStatus {
    PENDING_REVIEW = "PENDING_REVIEW",
    APPROVED = "APPROVED",
    REJECTED = "REJECTED"
}
export declare enum MappingEvidenceSource {
    INTERNAL_APPROVED = "INTERNAL_APPROVED",
    SOURCE_PLATFORM_OFFICIAL_DOCS = "SOURCE_PLATFORM_OFFICIAL_DOCS",
    TARGET_PLATFORM_OFFICIAL_DOCS = "TARGET_PLATFORM_OFFICIAL_DOCS",
    OFFICIAL_OPENAPI_SPEC = "OFFICIAL_OPENAPI_SPEC",
    OFFICIAL_FIELD_DICTIONARY = "OFFICIAL_FIELD_DICTIONARY",
    CURATED_SCHEMA_PACK = "CURATED_SCHEMA_PACK"
}
export declare enum RunStatus {
    PENDING = "PENDING",
    RUNNING = "RUNNING",
    SUCCESS = "SUCCESS",
    FAILED = "FAILED",
    RETRYING = "RETRYING",
    CANCELLED = "CANCELLED"
}
export declare enum AuditAction {
    MAPPING_APPROVED = "MAPPING_APPROVED",
    MAPPING_REJECTED = "MAPPING_REJECTED",
    RELEASE_SUBMITTED = "RELEASE_SUBMITTED",
    RELEASE_APPROVED = "RELEASE_APPROVED",
    RELEASE_REJECTED = "RELEASE_REJECTED",
    RELEASE_DEPLOYED = "RELEASE_DEPLOYED",
    INTEGRATION_CREATED = "INTEGRATION_CREATED",
    INTEGRATION_PAUSED = "INTEGRATION_PAUSED",
    INTEGRATION_RESUMED = "INTEGRATION_RESUMED",
    CONNECTION_TESTED = "CONNECTION_TESTED",
    RUN_REPLAYED = "RUN_REPLAYED"
}
//# sourceMappingURL=index.d.ts.map