import { type BuilderState, type StepMeta } from './types';

export const DEFAULT_STEPS: StepMeta[] = [
  { id: 'trigger', label: 'Trigger', nodeKey: 'trigger', status: 'not-started' },
  { id: 'sourceGroup', label: 'Sources', nodeKey: 'sourceGroup', status: 'not-started' },
  { id: 'mapping', label: 'Mapping', nodeKey: 'mapping', status: 'not-started' },
  { id: 'validation', label: 'Validation', nodeKey: 'validation', status: 'not-started' },
  { id: 'targetGroup', label: 'Targets', nodeKey: 'targetGroup', status: 'not-started' },
  { id: 'responseHandling', label: 'Responses', nodeKey: 'responseHandling', status: 'not-started' },
  { id: 'operations', label: 'Ops', nodeKey: 'operations', status: 'not-started' },
];

export function createBlankBuilderState(integrationId: string, name: string): BuilderState {
  return {
    integrationId,
    integrationName: name,
    templateLabel: '',
    versionLabel: 'v1.0 Draft',
    validationStatus: 'Not validated',
    environment: 'Dev',
    activeStep: 'trigger',
    steps: DEFAULT_STEPS.map((s) => ({ ...s })),
    trigger: {
      triggerType: 'Schedule / Cron',
      cronExpression: '',
      timezone: 'UTC',
      webhookPath: '',
      webhookMethod: 'POST',
      manualExecutionEnabled: true,
      description: '',
    },
    sourceGroup: {
      primary: {
        connectionId: '',
        connectionName: '',
        connectionFamily: '',
        healthStatus: '',
        businessObject: '',
        operation: 'GET',
        endpointPath: '',
        queryParams: [],
        headers: [],
        customParams: [],
        paginationEnabled: false,
        paginationStrategy: 'None',
        pageSize: 100,
        incrementalReadMode: 'Off',
      },
      enrichmentSources: [],
      processingPattern: 'Single Source',
    },
    mapping: { mappings: [], unmappedSourceFields: [], unmappedTargetFields: [] },
    validation: { rules: [], policyMode: 'Balanced', errorConfig: { logEnabled: true, dlqEnabled: false, dlqTopic: '', notifyChannel: 'None', notifyRecipients: '', includeRecordData: false } },
    targetGroup: { targets: [], deliveryPattern: 'Single Target', targetProfileState: null },
    responseHandling: {
      successCriteria: 'any_success',
      storeResponse: true,
      transformResponse: false,
      outputToSource: 'auto_if_expected',
      notificationEnabled: false,
      notificationDestinationUrl: '',
      notificationMethod: 'POST',
      notificationOnSuccess: true,
      notificationOnFailure: true,
      notificationPayloadMode: 'standard_response',
      businessErrorTranslationEnabled: false,
      loggingLevel: 'Standard',
      debugMode: false,
    },
    operations: {
      storeRunHistory: true,
      storeErrorDetails: true,
      storePayloadSnapshots: false,
      retentionDays: 30,
      failureBehavior: 'retry',
      retryAttempts: 3,
      retryInterval: '5 min',
      partialSuccessPolicy: 'fail_entire_transaction',
      afterFinalFailureNotify: true,
      afterFinalFailureMarkFailed: true,
      afterFinalFailureMoveToQueue: false,
      notifyOnFirstFailure: true,
      notifyAfterFinalFailure: true,
      notifyOnSuccess: false,
      alertRecipients: '',
      notificationType: 'None',
      enableDetailedDiagnostics: false,
      includePayloadInAlerts: false,
      loggingLevel: 'Standard',
      debugMode: false,
    },
    isDirty: false,
    isSaving: false,
    lastSavedAt: null,
    selectedMappingId: null,
    selectedRuleId: null,
  };
}
